// Copies the vault IDL from `anchor build` output (target/) into src/idl/vault.ts, so the
// package does not depend on a local build. Run after changing the program:
//   pnpm build:program && pnpm --filter @solana-symphony/vault-client sync-idl
// src/idl/sync.test.ts fails while the copy is out of date.
import { readFileSync, writeFileSync } from "node:fs";
import process from "node:process";
import { fileURLToPath, URL } from "node:url";

const root = fileURLToPath(new URL("../../../", import.meta.url));
const json = readFileSync(`${root}target/idl/vault.json`, "utf8");
const types = readFileSync(`${root}target/types/vault.ts`, "utf8");

writeFileSync(
  fileURLToPath(new URL("../src/idl/vault.ts", import.meta.url)),
  `// GENERATED by scripts/sync-idl.mjs from target/idl/vault.json and target/types/vault.ts.
// Do not edit; run \`pnpm --filter @solana-symphony/vault-client sync-idl\` instead.

${types.trim()}

/** The vault program's IDL (snake_case JSON, as Anchor's Program expects). */
export const VAULT_IDL = ${json.trim()} as unknown as Vault;
`,
);
process.stdout.write("synced src/idl/vault.ts from target/\n");
