skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
vault = "9rH4ChbiGz7QzTQBJ89VvgLMA8xf2jjjcW5TZXffC7x3"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
