// GENERATED by scripts/sync-idl.mjs from target/idl/vault.json and target/types/vault.ts.
// Do not edit; run `pnpm --filter @solana-symphony/vault-client sync-idl` instead.

/**
 * Program IDL in camelCase format in order to be used in JS/TS.
 *
 * Note that this is only a type helper and is not the actual IDL. The original
 * IDL can be found at `target/idl/vault.json`.
 */
export type Vault = {
  address: "5RAyigJyfZDreAfJsGufXcgtRraMq1hrEp3sm2nZqsHG";
  metadata: {
    name: "vault";
    version: "0.1.0";
    spec: "0.1.0";
    description: "On-chain vault for solana-symphony: owner-custodied, keeper-rebalanced via Jupiter";
  };
  instructions: [
    {
      name: "deposit";
      docs: [
        "Moves tokens from the owner into the vault's ATA, creating it if needed",
        "(owner only, allowed mints only; works while paused).",
      ];
      discriminator: [242, 35, 198, 137, 82, 225, 242, 182];
      accounts: [
        {
          name: "owner";
          writable: true;
          signer: true;
          relations: ["vault"];
        },
        {
          name: "vault";
          pda: {
            seeds: [
              {
                kind: "const";
                value: [118, 97, 117, 108, 116];
              },
              {
                kind: "account";
                path: "vault.owner";
                account: "vault";
              },
              {
                kind: "account";
                path: "vault.vaultId";
                account: "vault";
              },
            ];
          };
        },
        {
          name: "mint";
        },
        {
          name: "ownerTokenAccount";
          writable: true;
        },
        {
          name: "vaultTokenAccount";
          writable: true;
          pda: {
            seeds: [
              {
                kind: "account";
                path: "vault";
              },
              {
                kind: "account";
                path: "tokenProgram";
              },
              {
                kind: "account";
                path: "mint";
              },
            ];
            program: {
              kind: "const";
              value: [
                140,
                151,
                37,
                143,
                78,
                36,
                137,
                241,
                187,
                61,
                16,
                41,
                20,
                142,
                13,
                131,
                11,
                90,
                19,
                153,
                218,
                255,
                16,
                132,
                4,
                142,
                123,
                216,
                219,
                233,
                248,
                89,
              ];
            };
          };
        },
        {
          name: "tokenProgram";
          address: "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA";
        },
        {
          name: "associatedTokenProgram";
          address: "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL";
        },
        {
          name: "systemProgram";
          address: "11111111111111111111111111111111";
        },
      ];
      args: [
        {
          name: "amount";
          type: "u64";
        },
      ];
    },
    {
      name: "initializeVault";
      docs: ["Creates a vault owned by the signer (owner only)."];
      discriminator: [48, 191, 163, 44, 71, 129, 63, 164];
      accounts: [
        {
          name: "owner";
          writable: true;
          signer: true;
        },
        {
          name: "vault";
          writable: true;
          pda: {
            seeds: [
              {
                kind: "const";
                value: [118, 97, 117, 108, 116];
              },
              {
                kind: "account";
                path: "owner";
              },
              {
                kind: "arg";
                path: "args.vaultId";
              },
            ];
          };
        },
        {
          name: "systemProgram";
          address: "11111111111111111111111111111111";
        },
      ];
      args: [
        {
          name: "args";
          type: {
            defined: {
              name: "initializeVaultArgs";
            };
          };
        },
      ];
    },
    {
      name: "setKeeper";
      docs: ["Sets or removes the keeper (owner only)."];
      discriminator: [102, 94, 23, 78, 157, 222, 243, 214];
      accounts: [
        {
          name: "owner";
          signer: true;
          relations: ["vault"];
        },
        {
          name: "vault";
          writable: true;
          pda: {
            seeds: [
              {
                kind: "const";
                value: [118, 97, 117, 108, 116];
              },
              {
                kind: "account";
                path: "vault.owner";
                account: "vault";
              },
              {
                kind: "account";
                path: "vault.vaultId";
                account: "vault";
              },
            ];
          };
        },
      ];
      args: [
        {
          name: "newKeeper";
          type: "pubkey";
        },
      ];
    },
    {
      name: "setPaused";
      docs: ["Pauses or resumes swaps (owner only)."];
      discriminator: [91, 60, 125, 192, 176, 225, 166, 218];
      accounts: [
        {
          name: "owner";
          signer: true;
          relations: ["vault"];
        },
        {
          name: "vault";
          writable: true;
          pda: {
            seeds: [
              {
                kind: "const";
                value: [118, 97, 117, 108, 116];
              },
              {
                kind: "account";
                path: "vault.owner";
                account: "vault";
              },
              {
                kind: "account";
                path: "vault.vaultId";
                account: "vault";
              },
            ];
          };
        },
      ];
      args: [
        {
          name: "paused";
          type: "bool";
        },
      ];
    },
    {
      name: "swap";
      docs: [
        "Swaps between two allowed mints (keeper only) through Jupiter v6, checked against Pyth",
        "prices: `route_data` and the remaining accounts are Jupiter's swap instruction. The",
        "TEST-ONLY `devnet-mock` build pins programs/mock-swap instead.",
      ];
      discriminator: [248, 198, 158, 145, 225, 117, 135, 200];
      accounts: [
        {
          name: "keeper";
          writable: true;
          signer: true;
        },
        {
          name: "vault";
          writable: true;
          pda: {
            seeds: [
              {
                kind: "const";
                value: [118, 97, 117, 108, 116];
              },
              {
                kind: "account";
                path: "vault.owner";
                account: "vault";
              },
              {
                kind: "account";
                path: "vault.vaultId";
                account: "vault";
              },
            ];
          };
        },
        {
          name: "inputMint";
        },
        {
          name: "outputMint";
        },
        {
          name: "vaultInputAccount";
          writable: true;
          pda: {
            seeds: [
              {
                kind: "account";
                path: "vault";
              },
              {
                kind: "account";
                path: "tokenProgram";
              },
              {
                kind: "account";
                path: "inputMint";
              },
            ];
            program: {
              kind: "const";
              value: [
                140,
                151,
                37,
                143,
                78,
                36,
                137,
                241,
                187,
                61,
                16,
                41,
                20,
                142,
                13,
                131,
                11,
                90,
                19,
                153,
                218,
                255,
                16,
                132,
                4,
                142,
                123,
                216,
                219,
                233,
                248,
                89,
              ];
            };
          };
        },
        {
          name: "vaultOutputAccount";
          writable: true;
          pda: {
            seeds: [
              {
                kind: "account";
                path: "vault";
              },
              {
                kind: "account";
                path: "tokenProgram";
              },
              {
                kind: "account";
                path: "outputMint";
              },
            ];
            program: {
              kind: "const";
              value: [
                140,
                151,
                37,
                143,
                78,
                36,
                137,
                241,
                187,
                61,
                16,
                41,
                20,
                142,
                13,
                131,
                11,
                90,
                19,
                153,
                218,
                255,
                16,
                132,
                4,
                142,
                123,
                216,
                219,
                233,
                248,
                89,
              ];
            };
          };
        },
        {
          name: "inputPriceUpdate";
          docs: [
            "Pyth price update for `input_mint`. Anchor checks the owner (the Pyth receiver",
            "program) and the account type; verification level, feed ID, staleness and confidence",
            "are checked in the handler with `price::read_price` (design §4.7 check 6).",
          ];
        },
        {
          name: "outputPriceUpdate";
          docs: ["Pyth price update for `output_mint`, validated like `input_price_update`."];
        },
        {
          name: "swapProgram";
          docs: ["TEST-ONLY `devnet-mock` build); checked in the handler before any CPI (§6.3)."];
        },
        {
          name: "tokenProgram";
          address: "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA";
        },
        {
          name: "associatedTokenProgram";
          address: "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL";
        },
      ];
      args: [
        {
          name: "amountIn";
          type: "u64";
        },
        {
          name: "keeperMinOut";
          type: "u64";
        },
        {
          name: "routeData";
          type: "bytes";
        },
      ];
    },
    {
      name: "updateConfig";
      docs: ["Changes allowed mints, slippage, staleness or strategy hash (owner only)."];
      discriminator: [29, 158, 252, 191, 10, 83, 219, 99];
      accounts: [
        {
          name: "owner";
          signer: true;
          relations: ["vault"];
        },
        {
          name: "vault";
          writable: true;
          pda: {
            seeds: [
              {
                kind: "const";
                value: [118, 97, 117, 108, 116];
              },
              {
                kind: "account";
                path: "vault.owner";
                account: "vault";
              },
              {
                kind: "account";
                path: "vault.vaultId";
                account: "vault";
              },
            ];
          };
        },
      ];
      args: [
        {
          name: "args";
          type: {
            defined: {
              name: "updateConfigArgs";
            };
          };
        },
      ];
    },
    {
      name: "withdraw";
      docs: [
        "Moves tokens from the vault's ATA to the owner's ATA, signed by the vault PDA",
        "(owner only; any mint; works while paused).",
      ];
      discriminator: [183, 18, 70, 156, 148, 109, 161, 34];
      accounts: [
        {
          name: "owner";
          signer: true;
          relations: ["vault"];
        },
        {
          name: "vault";
          pda: {
            seeds: [
              {
                kind: "const";
                value: [118, 97, 117, 108, 116];
              },
              {
                kind: "account";
                path: "vault.owner";
                account: "vault";
              },
              {
                kind: "account";
                path: "vault.vaultId";
                account: "vault";
              },
            ];
          };
        },
        {
          name: "mint";
        },
        {
          name: "vaultTokenAccount";
          writable: true;
          pda: {
            seeds: [
              {
                kind: "account";
                path: "vault";
              },
              {
                kind: "account";
                path: "tokenProgram";
              },
              {
                kind: "account";
                path: "mint";
              },
            ];
            program: {
              kind: "const";
              value: [
                140,
                151,
                37,
                143,
                78,
                36,
                137,
                241,
                187,
                61,
                16,
                41,
                20,
                142,
                13,
                131,
                11,
                90,
                19,
                153,
                218,
                255,
                16,
                132,
                4,
                142,
                123,
                216,
                219,
                233,
                248,
                89,
              ];
            };
          };
        },
        {
          name: "ownerTokenAccount";
          writable: true;
          pda: {
            seeds: [
              {
                kind: "account";
                path: "owner";
              },
              {
                kind: "account";
                path: "tokenProgram";
              },
              {
                kind: "account";
                path: "mint";
              },
            ];
            program: {
              kind: "const";
              value: [
                140,
                151,
                37,
                143,
                78,
                36,
                137,
                241,
                187,
                61,
                16,
                41,
                20,
                142,
                13,
                131,
                11,
                90,
                19,
                153,
                218,
                255,
                16,
                132,
                4,
                142,
                123,
                216,
                219,
                233,
                248,
                89,
              ];
            };
          };
        },
        {
          name: "tokenProgram";
          address: "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA";
        },
        {
          name: "associatedTokenProgram";
          address: "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL";
        },
      ];
      args: [
        {
          name: "amount";
          type: "u64";
        },
      ];
    },
  ];
  accounts: [
    {
      name: "vault";
      discriminator: [211, 8, 232, 43, 2, 152, 117, 119];
    },
  ];
  events: [
    {
      name: "configUpdated";
      discriminator: [40, 241, 230, 122, 11, 19, 198, 194];
    },
    {
      name: "deposited";
      discriminator: [111, 141, 26, 45, 161, 35, 100, 57];
    },
    {
      name: "keeperChanged";
      discriminator: [194, 174, 248, 100, 222, 104, 243, 108];
    },
    {
      name: "pausedChanged";
      discriminator: [12, 10, 153, 247, 60, 115, 137, 69];
    },
    {
      name: "swapped";
      discriminator: [217, 52, 52, 83, 147, 135, 96, 109];
    },
    {
      name: "vaultInitialized";
      discriminator: [180, 43, 207, 2, 18, 71, 3, 75];
    },
    {
      name: "withdrawn";
      discriminator: [20, 89, 223, 198, 194, 124, 219, 13];
    },
  ];
  errors: [
    {
      code: 6000;
      name: "unauthorized";
      msg: "Only the vault owner can do this";
    },
    {
      code: 6001;
      name: "notKeeper";
      msg: "Only the vault's keeper can swap";
    },
    {
      code: 6002;
      name: "keeperNotSet";
      msg: "This vault has no keeper set, so swaps are disabled";
    },
    {
      code: 6003;
      name: "vaultPaused";
      msg: "The vault is paused: swaps are disabled (deposits and withdrawals still work)";
    },
    {
      code: 6004;
      name: "mintNotAllowed";
      msg: "This mint is not in the vault's allowed mints";
    },
    {
      code: 6005;
      name: "sameMint";
      msg: "Swap input and output mints must be different";
    },
    {
      code: 6006;
      name: "invalidMintCount";
      msg: "A vault must allow between 1 and 10 mints";
    },
    {
      code: 6007;
      name: "duplicateMint";
      msg: "Each mint may appear only once in the allowed mints";
    },
    {
      code: 6008;
      name: "duplicateFeed";
      msg: "Each Pyth feed may be used by only one allowed mint";
    },
    {
      code: 6009;
      name: "mintAccountsMismatch";
      msg: "Pass one mint account per allowed mint, in the same order as allowed_mints";
    },
    {
      code: 6010;
      name: "invalidMint";
      msg: "Account is not an initialized SPL Token mint";
    },
    {
      code: 6011;
      name: "unsupportedTokenProgram";
      msg: "Only classic SPL Token mints are supported (not Token-2022)";
    },
    {
      code: 6012;
      name: "invalidTokenAccount";
      msg: "Token account is not the vault's associated token account for this mint";
    },
    {
      code: 6013;
      name: "invalidDestination";
      msg: "Withdrawals can only go to a token account owned by the vault owner";
    },
    {
      code: 6014;
      name: "zeroAmount";
      msg: "Amount must be greater than zero";
    },
    {
      code: 6015;
      name: "insufficientBalance";
      msg: "The vault does not hold enough of this token";
    },
    {
      code: 6016;
      name: "slippageAboveCap";
      msg: "max_slippage_bps must be between 1 and 500 (5%)";
    },
    {
      code: 6017;
      name: "stalenessAboveCap";
      msg: "max_oracle_staleness_secs must be between 1 and 120";
    },
    {
      code: 6018;
      name: "invalidOracleAccount";
      msg: "Price account is not a verified Pyth price update";
    },
    {
      code: 6019;
      name: "oracleFeedMismatch";
      msg: "Price update is for a different feed than this mint's configured Pyth feed";
    },
    {
      code: 6020;
      name: "stalePrice";
      msg: "Price is older than the vault's max_oracle_staleness_secs";
    },
    {
      code: 6021;
      name: "priceTooUncertain";
      msg: "Price confidence interval is wider than 2% of the price";
    },
    {
      code: 6022;
      name: "nonPositivePrice";
      msg: "Oracle price must be positive";
    },
    {
      code: 6023;
      name: "invalidSwapProgram";
      msg: "Swaps may only call the Jupiter program";
    },
    {
      code: 6024;
      name: "forbiddenRouteAccount";
      msg: "Swap route includes a vault token account other than the input and output";
    },
    {
      code: 6025;
      name: "spentMoreThanAmountIn";
      msg: "Swap spent more of the input token than amount_in";
    },
    {
      code: 6026;
      name: "nothingReceived";
      msg: "Swap delivered nothing to the vault's output account";
    },
    {
      code: 6027;
      name: "outputBelowMinimum";
      msg: "Swap output is below the oracle-based minimum (or the keeper's minimum)";
    },
    {
      code: 6028;
      name: "tokenAccountTampered";
      msg: "A vault token account's authority, delegate or close authority changed during the swap";
    },
    {
      code: 6029;
      name: "swapCooldown";
      msg: "Too soon since the last swap: wait for the swap cooldown";
    },
    {
      code: 6030;
      name: "mathOverflow";
      msg: "Arithmetic overflow";
    },
    {
      code: 6031;
      name: "notImplemented";
      msg: "Not implemented yet";
    },
    {
      code: 6032;
      name: "dailyLossLimitExceeded";
      msg: "This swap's loss against the oracle would exceed the vault's daily loss limit";
    },
    {
      code: 6033;
      name: "priceSkewTooLarge";
      msg: "The input and output price updates were published too far apart";
    },
  ];
  types: [
    {
      name: "allowedMint";
      docs: ["A mint the vault may hold and swap, with the Pyth feed that prices it in USD."];
      type: {
        kind: "struct";
        fields: [
          {
            name: "mint";
            docs: ["Classic SPL Token mint (Token-2022 is rejected, design §6.8)."];
            type: "pubkey";
          },
          {
            name: "pythFeedId";
            docs: [
              "Pyth USD price feed ID for this mint, e.g. SOL/USD for wSOL. The swap reads the",
              "price only from an update for this feed, so the keeper cannot choose the price.",
            ];
            type: {
              array: ["u8", 32];
            };
          },
        ];
      };
    },
    {
      name: "configUpdated";
      type: {
        kind: "struct";
        fields: [
          {
            name: "vault";
            type: "pubkey";
          },
          {
            name: "allowedMints";
            type: {
              vec: {
                defined: {
                  name: "allowedMint";
                };
              };
            };
          },
          {
            name: "maxSlippageBps";
            type: "u16";
          },
          {
            name: "maxOracleStalenessSecs";
            type: "u32";
          },
          {
            name: "strategyHash";
            type: {
              array: ["u8", 32];
            };
          },
          {
            name: "maxDailyLossUsd";
            type: "u64";
          },
        ];
      };
    },
    {
      name: "deposited";
      type: {
        kind: "struct";
        fields: [
          {
            name: "vault";
            type: "pubkey";
          },
          {
            name: "mint";
            type: "pubkey";
          },
          {
            name: "amount";
            type: "u64";
          },
          {
            name: "vaultBalance";
            docs: ["Vault balance of `mint` after the deposit."];
            type: "u64";
          },
        ];
      };
    },
    {
      name: "initializeVaultArgs";
      type: {
        kind: "struct";
        fields: [
          {
            name: "vaultId";
            type: "u64";
          },
          {
            name: "keeper";
            docs: ["`Pubkey::default()` for no keeper (swaps disabled until set_keeper)."];
            type: "pubkey";
          },
          {
            name: "allowedMints";
            type: {
              vec: {
                defined: {
                  name: "allowedMint";
                };
              };
            };
          },
          {
            name: "maxSlippageBps";
            type: "u16";
          },
          {
            name: "maxOracleStalenessSecs";
            type: "u32";
          },
          {
            name: "strategyHash";
            type: {
              array: ["u8", 32];
            };
          },
          {
            name: "maxDailyLossUsd";
            docs: [
              "Most the vault may lose to swaps per 24 hours versus the oracle, in micro-USD.",
              "0 allows no loss at all (every swap must match or beat the oracle).",
            ];
            type: "u64";
          },
        ];
      };
    },
    {
      name: "keeperChanged";
      type: {
        kind: "struct";
        fields: [
          {
            name: "vault";
            type: "pubkey";
          },
          {
            name: "oldKeeper";
            type: "pubkey";
          },
          {
            name: "newKeeper";
            type: "pubkey";
          },
        ];
      };
    },
    {
      name: "pausedChanged";
      type: {
        kind: "struct";
        fields: [
          {
            name: "vault";
            type: "pubkey";
          },
          {
            name: "paused";
            type: "bool";
          },
        ];
      };
    },
    {
      name: "priceFeedMessage";
      repr: {
        kind: "c";
      };
      type: {
        kind: "struct";
        fields: [
          {
            name: "feedId";
            docs: [
              "`FeedId` but avoid the type alias because of compatibility issues with Anchor's `idl-build` feature.",
            ];
            type: {
              array: ["u8", 32];
            };
          },
          {
            name: "price";
            type: "i64";
          },
          {
            name: "conf";
            type: "u64";
          },
          {
            name: "exponent";
            type: "i32";
          },
          {
            name: "publishTime";
            docs: ["The timestamp of this price update in seconds"];
            type: "i64";
          },
          {
            name: "prevPublishTime";
            docs: [
              "The timestamp of the previous price update. This field is intended to allow users to",
              "identify the single unique price update for any moment in time:",
              "for any time t, the unique update is the one such that prev_publish_time < t <= publish_time.",
              "",
              "Note that there may not be such an update while we are migrating to the new message-sending logic,",
              "as some price updates on pythnet may not be sent to other chains (because the message-sending",
              "logic may not have triggered). We can solve this problem by making the message-sending mandatory",
              "(which we can do once publishers have migrated over).",
              "",
              "Additionally, this field may be equal to publish_time if the message is sent on a slot where",
              "where the aggregation was unsuccesful. This problem will go away once all publishers have",
              "migrated over to a recent version of pyth-agent.",
            ];
            type: "i64";
          },
          {
            name: "emaPrice";
            type: "i64";
          },
          {
            name: "emaConf";
            type: "u64";
          },
        ];
      };
    },
    {
      name: "priceUpdateV2";
      docs: [
        "A price update account. This account is used by the Pyth Receiver program to store a verified price update from a Pyth price feed.",
        "It contains:",
        "- `write_authority`: The write authority for this account. This authority can close this account to reclaim rent or update the account to contain a different price update.",
        "- `verification_level`: The [`VerificationLevel`] of this price update. This represents how many Wormhole guardian signatures have been verified for this price update.",
        "- `price_message`: The actual price update.",
        "- `posted_slot`: The slot at which this price update was posted.",
      ];
      type: {
        kind: "struct";
        fields: [
          {
            name: "writeAuthority";
            type: "pubkey";
          },
          {
            name: "verificationLevel";
            type: {
              defined: {
                name: "verificationLevel";
              };
            };
          },
          {
            name: "priceMessage";
            type: {
              defined: {
                name: "priceFeedMessage";
              };
            };
          },
          {
            name: "postedSlot";
            type: "u64";
          },
        ];
      };
    },
    {
      name: "swapped";
      docs: ["Everything needed to audit a swap against the oracle afterwards."];
      type: {
        kind: "struct";
        fields: [
          {
            name: "vault";
            type: "pubkey";
          },
          {
            name: "keeper";
            type: "pubkey";
          },
          {
            name: "inputMint";
            type: "pubkey";
          },
          {
            name: "outputMint";
            type: "pubkey";
          },
          {
            name: "spent";
            docs: ["Input actually spent (base units)."];
            type: "u64";
          },
          {
            name: "received";
            docs: ["Output actually received by the vault (base units)."];
            type: "u64";
          },
          {
            name: "oracleOut";
            docs: ["Output the oracle prices imply for `spent`, before slippage."];
            type: "u64";
          },
          {
            name: "minOut";
            docs: ["The minimum the swap had to meet."];
            type: "u64";
          },
          {
            name: "priceIn";
            type: "i64";
          },
          {
            name: "priceInExpo";
            type: "i32";
          },
          {
            name: "priceOut";
            type: "i64";
          },
          {
            name: "priceOutExpo";
            type: "i32";
          },
          {
            name: "lossUsd";
            docs: [
              "This swap's shortfall versus the oracle, in micro-USD (0 if it met or beat it).",
            ];
            type: "u64";
          },
          {
            name: "lossInWindowUsd";
            docs: ["Losses in the current 24-hour window including this swap, in micro-USD."];
            type: "u64";
          },
        ];
      };
    },
    {
      name: "updateConfigArgs";
      docs: ["Fields left as `None` are unchanged."];
      type: {
        kind: "struct";
        fields: [
          {
            name: "allowedMints";
            type: {
              option: {
                vec: {
                  defined: {
                    name: "allowedMint";
                  };
                };
              };
            };
          },
          {
            name: "maxSlippageBps";
            type: {
              option: "u16";
            };
          },
          {
            name: "maxOracleStalenessSecs";
            type: {
              option: "u32";
            };
          },
          {
            name: "strategyHash";
            type: {
              option: {
                array: ["u8", 32];
              };
            };
          },
          {
            name: "maxDailyLossUsd";
            docs: [
              "Micro-USD per 24 hours; takes effect immediately, losses already counted stay counted.",
            ];
            type: {
              option: "u64";
            };
          },
        ];
      };
    },
    {
      name: "vault";
      docs: [
        'One owner\'s vault. PDA seeds: `["vault", owner, vault_id.to_le_bytes()]`.',
        "",
        "Tokens are held in the vault PDA's associated token accounts, one per mint. The owner",
        "deposits, withdraws and configures; the keeper may only swap between allowed mints.",
      ];
      type: {
        kind: "struct";
        fields: [
          {
            name: "owner";
            docs: ["Signs every instruction except `swap`. Immutable."];
            type: "pubkey";
          },
          {
            name: "vaultId";
            docs: ["Part of the PDA seeds, so one owner can have several vaults. Immutable."];
            type: "u64";
          },
          {
            name: "keeper";
            docs: ["The only key that may call `swap`. `Pubkey::default()` means no keeper."];
            type: "pubkey";
          },
          {
            name: "allowedMints";
            docs: ["Mints the vault may receive by deposit or swap. No duplicates."];
            type: {
              vec: {
                defined: {
                  name: "allowedMint";
                };
              };
            };
          },
          {
            name: "maxSlippageBps";
            docs: ["Largest shortfall a swap may have versus the oracle value, in bps."];
            type: "u16";
          },
          {
            name: "maxOracleStalenessSecs";
            docs: ["Oldest price a swap may use, in seconds."];
            type: "u32";
          },
          {
            name: "strategyHash";
            docs: ["SHA-256 of the strategy JSON the owner approved. Informational, not enforced."];
            type: {
              array: ["u8", 32];
            };
          },
          {
            name: "paused";
            docs: ["When true, `swap` is blocked. Deposits and withdrawals still work."];
            type: "bool";
          },
          {
            name: "lastSwapTs";
            docs: ["Unix time of the last swap, for the swap cooldown."];
            type: "i64";
          },
          {
            name: "bump";
            docs: ["Canonical PDA bump."];
            type: "u8";
          },
          {
            name: "maxDailyLossUsd";
            docs: [
              "Most the vault may lose to swaps per 24 hours, versus the oracle, in micro-USD",
              "(USD × 10^6). Bounds what a compromised keeper can extract (security review H-1).",
            ];
            type: "u64";
          },
          {
            name: "lossWindowStart";
            docs: ["Start (unix seconds) of the current 24-hour loss window."];
            type: "i64";
          },
          {
            name: "lossInWindowUsd";
            docs: ["Losses counted in the current window, in micro-USD."];
            type: "u64";
          },
          {
            name: "reserved";
            docs: ["Space for future fields without reallocating."];
            type: {
              array: ["u8", 40];
            };
          },
        ];
      };
    },
    {
      name: "vaultInitialized";
      type: {
        kind: "struct";
        fields: [
          {
            name: "vault";
            type: "pubkey";
          },
          {
            name: "owner";
            type: "pubkey";
          },
          {
            name: "vaultId";
            type: "u64";
          },
          {
            name: "keeper";
            type: "pubkey";
          },
          {
            name: "allowedMints";
            type: {
              vec: {
                defined: {
                  name: "allowedMint";
                };
              };
            };
          },
          {
            name: "maxSlippageBps";
            type: "u16";
          },
          {
            name: "maxOracleStalenessSecs";
            type: "u32";
          },
          {
            name: "strategyHash";
            type: {
              array: ["u8", 32];
            };
          },
          {
            name: "maxDailyLossUsd";
            type: "u64";
          },
        ];
      };
    },
    {
      name: "verificationLevel";
      docs: [
        "Pyth price updates are bridged to all blockchains via Wormhole.",
        "Using the price updates on another chain requires verifying the signatures of the Wormhole guardians.",
        "The usual process is to check the signatures for two thirds of the total number of guardians, but this can be cumbersome on Solana because of the transaction size limits,",
        "so we also allow for partial verification.",
        "",
        "This enum represents how much a price update has been verified:",
        "- If `Full`, we have verified the signatures for two thirds of the current guardians.",
        "- If `Partial`, only `num_signatures` guardian signatures have been checked.",
        "",
        "# Warning",
        "Using partially verified price updates is dangerous, as it lowers the threshold of guardians that need to collude to produce a malicious price update.",
      ];
      type: {
        kind: "enum";
        variants: [
          {
            name: "partial";
            fields: [
              {
                name: "numSignatures";
                type: "u8";
              },
            ];
          },
          {
            name: "full";
          },
        ];
      };
    },
    {
      name: "withdrawn";
      type: {
        kind: "struct";
        fields: [
          {
            name: "vault";
            type: "pubkey";
          },
          {
            name: "mint";
            type: "pubkey";
          },
          {
            name: "amount";
            type: "u64";
          },
          {
            name: "destination";
            type: "pubkey";
          },
          {
            name: "vaultBalance";
            docs: ["Vault balance of `mint` after the withdrawal."];
            type: "u64";
          },
        ];
      };
    },
  ];
  constants: [
    {
      name: "lossWindowSecs";
      docs: ["Length of the window `max_daily_loss_usd` applies to (security review H-1)."];
      type: "i64";
      value: "86400";
    },
    {
      name: "maxConfidenceBps";
      docs: [
        "Reject a price whose confidence interval is wider than 2% of the price (design §3, Q3).",
      ];
      type: "u64";
      value: "200";
    },
    {
      name: "maxPriceSkewSecs";
      docs: [
        "The input and output price updates of one swap must be published at most this far apart,",
        "so the keeper cannot pair prices from different moments (security review M-1).",
      ];
      type: "i64";
      value: "30";
    },
    {
      name: "maxSlippageCapBps";
      docs: ["Hard ceiling on `max_slippage_bps` an owner can set: 5% (design §3, Q2)."];
      type: "u16";
      value: "500";
    },
    {
      name: "maxStalenessCapSecs";
      docs: ["Hard ceiling on `max_oracle_staleness_secs` an owner can set (design §3, Q2)."];
      type: "u32";
      value: "120";
    },
    {
      name: "minSwapIntervalSecs";
      docs: ["Minimum time between swaps on one vault, limiting fee bleed (design §6.15, Q5)."];
      type: "i64";
      value: "60";
    },
    {
      name: "vaultSeed";
      docs: ['PDA seed prefix: `["vault", owner, vault_id.to_le_bytes()]`.'];
      type: "bytes";
      value: "[118, 97, 117, 108, 116]";
    },
  ];
};

/** The vault program's IDL (snake_case JSON, as Anchor's Program expects). */
export const VAULT_IDL = {
  address: "5RAyigJyfZDreAfJsGufXcgtRraMq1hrEp3sm2nZqsHG",
  metadata: {
    name: "vault",
    version: "0.1.0",
    spec: "0.1.0",
    description:
      "On-chain vault for solana-symphony: owner-custodied, keeper-rebalanced via Jupiter",
  },
  instructions: [
    {
      name: "deposit",
      docs: [
        "Moves tokens from the owner into the vault's ATA, creating it if needed",
        "(owner only, allowed mints only; works while paused).",
      ],
      discriminator: [242, 35, 198, 137, 82, 225, 242, 182],
      accounts: [
        {
          name: "owner",
          writable: true,
          signer: true,
          relations: ["vault"],
        },
        {
          name: "vault",
          pda: {
            seeds: [
              {
                kind: "const",
                value: [118, 97, 117, 108, 116],
              },
              {
                kind: "account",
                path: "vault.owner",
                account: "Vault",
              },
              {
                kind: "account",
                path: "vault.vault_id",
                account: "Vault",
              },
            ],
          },
        },
        {
          name: "mint",
        },
        {
          name: "owner_token_account",
          writable: true,
        },
        {
          name: "vault_token_account",
          writable: true,
          pda: {
            seeds: [
              {
                kind: "account",
                path: "vault",
              },
              {
                kind: "account",
                path: "token_program",
              },
              {
                kind: "account",
                path: "mint",
              },
            ],
            program: {
              kind: "const",
              value: [
                140, 151, 37, 143, 78, 36, 137, 241, 187, 61, 16, 41, 20, 142, 13, 131, 11, 90, 19,
                153, 218, 255, 16, 132, 4, 142, 123, 216, 219, 233, 248, 89,
              ],
            },
          },
        },
        {
          name: "token_program",
          address: "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
        },
        {
          name: "associated_token_program",
          address: "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL",
        },
        {
          name: "system_program",
          address: "11111111111111111111111111111111",
        },
      ],
      args: [
        {
          name: "amount",
          type: "u64",
        },
      ],
    },
    {
      name: "initialize_vault",
      docs: ["Creates a vault owned by the signer (owner only)."],
      discriminator: [48, 191, 163, 44, 71, 129, 63, 164],
      accounts: [
        {
          name: "owner",
          writable: true,
          signer: true,
        },
        {
          name: "vault",
          writable: true,
          pda: {
            seeds: [
              {
                kind: "const",
                value: [118, 97, 117, 108, 116],
              },
              {
                kind: "account",
                path: "owner",
              },
              {
                kind: "arg",
                path: "args.vault_id",
              },
            ],
          },
        },
        {
          name: "system_program",
          address: "11111111111111111111111111111111",
        },
      ],
      args: [
        {
          name: "args",
          type: {
            defined: {
              name: "InitializeVaultArgs",
            },
          },
        },
      ],
    },
    {
      name: "set_keeper",
      docs: ["Sets or removes the keeper (owner only)."],
      discriminator: [102, 94, 23, 78, 157, 222, 243, 214],
      accounts: [
        {
          name: "owner",
          signer: true,
          relations: ["vault"],
        },
        {
          name: "vault",
          writable: true,
          pda: {
            seeds: [
              {
                kind: "const",
                value: [118, 97, 117, 108, 116],
              },
              {
                kind: "account",
                path: "vault.owner",
                account: "Vault",
              },
              {
                kind: "account",
                path: "vault.vault_id",
                account: "Vault",
              },
            ],
          },
        },
      ],
      args: [
        {
          name: "new_keeper",
          type: "pubkey",
        },
      ],
    },
    {
      name: "set_paused",
      docs: ["Pauses or resumes swaps (owner only)."],
      discriminator: [91, 60, 125, 192, 176, 225, 166, 218],
      accounts: [
        {
          name: "owner",
          signer: true,
          relations: ["vault"],
        },
        {
          name: "vault",
          writable: true,
          pda: {
            seeds: [
              {
                kind: "const",
                value: [118, 97, 117, 108, 116],
              },
              {
                kind: "account",
                path: "vault.owner",
                account: "Vault",
              },
              {
                kind: "account",
                path: "vault.vault_id",
                account: "Vault",
              },
            ],
          },
        },
      ],
      args: [
        {
          name: "paused",
          type: "bool",
        },
      ],
    },
    {
      name: "swap",
      docs: [
        "Swaps between two allowed mints (keeper only) through Jupiter v6, checked against Pyth",
        "prices: `route_data` and the remaining accounts are Jupiter's swap instruction. The",
        "TEST-ONLY `devnet-mock` build pins programs/mock-swap instead.",
      ],
      discriminator: [248, 198, 158, 145, 225, 117, 135, 200],
      accounts: [
        {
          name: "keeper",
          writable: true,
          signer: true,
        },
        {
          name: "vault",
          writable: true,
          pda: {
            seeds: [
              {
                kind: "const",
                value: [118, 97, 117, 108, 116],
              },
              {
                kind: "account",
                path: "vault.owner",
                account: "Vault",
              },
              {
                kind: "account",
                path: "vault.vault_id",
                account: "Vault",
              },
            ],
          },
        },
        {
          name: "input_mint",
        },
        {
          name: "output_mint",
        },
        {
          name: "vault_input_account",
          writable: true,
          pda: {
            seeds: [
              {
                kind: "account",
                path: "vault",
              },
              {
                kind: "account",
                path: "token_program",
              },
              {
                kind: "account",
                path: "input_mint",
              },
            ],
            program: {
              kind: "const",
              value: [
                140, 151, 37, 143, 78, 36, 137, 241, 187, 61, 16, 41, 20, 142, 13, 131, 11, 90, 19,
                153, 218, 255, 16, 132, 4, 142, 123, 216, 219, 233, 248, 89,
              ],
            },
          },
        },
        {
          name: "vault_output_account",
          writable: true,
          pda: {
            seeds: [
              {
                kind: "account",
                path: "vault",
              },
              {
                kind: "account",
                path: "token_program",
              },
              {
                kind: "account",
                path: "output_mint",
              },
            ],
            program: {
              kind: "const",
              value: [
                140, 151, 37, 143, 78, 36, 137, 241, 187, 61, 16, 41, 20, 142, 13, 131, 11, 90, 19,
                153, 218, 255, 16, 132, 4, 142, 123, 216, 219, 233, 248, 89,
              ],
            },
          },
        },
        {
          name: "input_price_update",
          docs: [
            "Pyth price update for `input_mint`. Anchor checks the owner (the Pyth receiver",
            "program) and the account type; verification level, feed ID, staleness and confidence",
            "are checked in the handler with `price::read_price` (design §4.7 check 6).",
          ],
        },
        {
          name: "output_price_update",
          docs: ["Pyth price update for `output_mint`, validated like `input_price_update`."],
        },
        {
          name: "swap_program",
          docs: ["TEST-ONLY `devnet-mock` build); checked in the handler before any CPI (§6.3)."],
        },
        {
          name: "token_program",
          address: "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
        },
        {
          name: "associated_token_program",
          address: "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL",
        },
      ],
      args: [
        {
          name: "amount_in",
          type: "u64",
        },
        {
          name: "keeper_min_out",
          type: "u64",
        },
        {
          name: "route_data",
          type: "bytes",
        },
      ],
    },
    {
      name: "update_config",
      docs: ["Changes allowed mints, slippage, staleness or strategy hash (owner only)."],
      discriminator: [29, 158, 252, 191, 10, 83, 219, 99],
      accounts: [
        {
          name: "owner",
          signer: true,
          relations: ["vault"],
        },
        {
          name: "vault",
          writable: true,
          pda: {
            seeds: [
              {
                kind: "const",
                value: [118, 97, 117, 108, 116],
              },
              {
                kind: "account",
                path: "vault.owner",
                account: "Vault",
              },
              {
                kind: "account",
                path: "vault.vault_id",
                account: "Vault",
              },
            ],
          },
        },
      ],
      args: [
        {
          name: "args",
          type: {
            defined: {
              name: "UpdateConfigArgs",
            },
          },
        },
      ],
    },
    {
      name: "withdraw",
      docs: [
        "Moves tokens from the vault's ATA to the owner's ATA, signed by the vault PDA",
        "(owner only; any mint; works while paused).",
      ],
      discriminator: [183, 18, 70, 156, 148, 109, 161, 34],
      accounts: [
        {
          name: "owner",
          signer: true,
          relations: ["vault"],
        },
        {
          name: "vault",
          pda: {
            seeds: [
              {
                kind: "const",
                value: [118, 97, 117, 108, 116],
              },
              {
                kind: "account",
                path: "vault.owner",
                account: "Vault",
              },
              {
                kind: "account",
                path: "vault.vault_id",
                account: "Vault",
              },
            ],
          },
        },
        {
          name: "mint",
        },
        {
          name: "vault_token_account",
          writable: true,
          pda: {
            seeds: [
              {
                kind: "account",
                path: "vault",
              },
              {
                kind: "account",
                path: "token_program",
              },
              {
                kind: "account",
                path: "mint",
              },
            ],
            program: {
              kind: "const",
              value: [
                140, 151, 37, 143, 78, 36, 137, 241, 187, 61, 16, 41, 20, 142, 13, 131, 11, 90, 19,
                153, 218, 255, 16, 132, 4, 142, 123, 216, 219, 233, 248, 89,
              ],
            },
          },
        },
        {
          name: "owner_token_account",
          writable: true,
          pda: {
            seeds: [
              {
                kind: "account",
                path: "owner",
              },
              {
                kind: "account",
                path: "token_program",
              },
              {
                kind: "account",
                path: "mint",
              },
            ],
            program: {
              kind: "const",
              value: [
                140, 151, 37, 143, 78, 36, 137, 241, 187, 61, 16, 41, 20, 142, 13, 131, 11, 90, 19,
                153, 218, 255, 16, 132, 4, 142, 123, 216, 219, 233, 248, 89,
              ],
            },
          },
        },
        {
          name: "token_program",
          address: "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
        },
        {
          name: "associated_token_program",
          address: "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL",
        },
      ],
      args: [
        {
          name: "amount",
          type: "u64",
        },
      ],
    },
  ],
  accounts: [
    {
      name: "Vault",
      discriminator: [211, 8, 232, 43, 2, 152, 117, 119],
    },
  ],
  events: [
    {
      name: "ConfigUpdated",
      discriminator: [40, 241, 230, 122, 11, 19, 198, 194],
    },
    {
      name: "Deposited",
      discriminator: [111, 141, 26, 45, 161, 35, 100, 57],
    },
    {
      name: "KeeperChanged",
      discriminator: [194, 174, 248, 100, 222, 104, 243, 108],
    },
    {
      name: "PausedChanged",
      discriminator: [12, 10, 153, 247, 60, 115, 137, 69],
    },
    {
      name: "Swapped",
      discriminator: [217, 52, 52, 83, 147, 135, 96, 109],
    },
    {
      name: "VaultInitialized",
      discriminator: [180, 43, 207, 2, 18, 71, 3, 75],
    },
    {
      name: "Withdrawn",
      discriminator: [20, 89, 223, 198, 194, 124, 219, 13],
    },
  ],
  errors: [
    {
      code: 6000,
      name: "Unauthorized",
      msg: "Only the vault owner can do this",
    },
    {
      code: 6001,
      name: "NotKeeper",
      msg: "Only the vault's keeper can swap",
    },
    {
      code: 6002,
      name: "KeeperNotSet",
      msg: "This vault has no keeper set, so swaps are disabled",
    },
    {
      code: 6003,
      name: "VaultPaused",
      msg: "The vault is paused: swaps are disabled (deposits and withdrawals still work)",
    },
    {
      code: 6004,
      name: "MintNotAllowed",
      msg: "This mint is not in the vault's allowed mints",
    },
    {
      code: 6005,
      name: "SameMint",
      msg: "Swap input and output mints must be different",
    },
    {
      code: 6006,
      name: "InvalidMintCount",
      msg: "A vault must allow between 1 and 10 mints",
    },
    {
      code: 6007,
      name: "DuplicateMint",
      msg: "Each mint may appear only once in the allowed mints",
    },
    {
      code: 6008,
      name: "DuplicateFeed",
      msg: "Each Pyth feed may be used by only one allowed mint",
    },
    {
      code: 6009,
      name: "MintAccountsMismatch",
      msg: "Pass one mint account per allowed mint, in the same order as allowed_mints",
    },
    {
      code: 6010,
      name: "InvalidMint",
      msg: "Account is not an initialized SPL Token mint",
    },
    {
      code: 6011,
      name: "UnsupportedTokenProgram",
      msg: "Only classic SPL Token mints are supported (not Token-2022)",
    },
    {
      code: 6012,
      name: "InvalidTokenAccount",
      msg: "Token account is not the vault's associated token account for this mint",
    },
    {
      code: 6013,
      name: "InvalidDestination",
      msg: "Withdrawals can only go to a token account owned by the vault owner",
    },
    {
      code: 6014,
      name: "ZeroAmount",
      msg: "Amount must be greater than zero",
    },
    {
      code: 6015,
      name: "InsufficientBalance",
      msg: "The vault does not hold enough of this token",
    },
    {
      code: 6016,
      name: "SlippageAboveCap",
      msg: "max_slippage_bps must be between 1 and 500 (5%)",
    },
    {
      code: 6017,
      name: "StalenessAboveCap",
      msg: "max_oracle_staleness_secs must be between 1 and 120",
    },
    {
      code: 6018,
      name: "InvalidOracleAccount",
      msg: "Price account is not a verified Pyth price update",
    },
    {
      code: 6019,
      name: "OracleFeedMismatch",
      msg: "Price update is for a different feed than this mint's configured Pyth feed",
    },
    {
      code: 6020,
      name: "StalePrice",
      msg: "Price is older than the vault's max_oracle_staleness_secs",
    },
    {
      code: 6021,
      name: "PriceTooUncertain",
      msg: "Price confidence interval is wider than 2% of the price",
    },
    {
      code: 6022,
      name: "NonPositivePrice",
      msg: "Oracle price must be positive",
    },
    {
      code: 6023,
      name: "InvalidSwapProgram",
      msg: "Swaps may only call the Jupiter program",
    },
    {
      code: 6024,
      name: "ForbiddenRouteAccount",
      msg: "Swap route includes a vault token account other than the input and output",
    },
    {
      code: 6025,
      name: "SpentMoreThanAmountIn",
      msg: "Swap spent more of the input token than amount_in",
    },
    {
      code: 6026,
      name: "NothingReceived",
      msg: "Swap delivered nothing to the vault's output account",
    },
    {
      code: 6027,
      name: "OutputBelowMinimum",
      msg: "Swap output is below the oracle-based minimum (or the keeper's minimum)",
    },
    {
      code: 6028,
      name: "TokenAccountTampered",
      msg: "A vault token account's authority, delegate or close authority changed during the swap",
    },
    {
      code: 6029,
      name: "SwapCooldown",
      msg: "Too soon since the last swap: wait for the swap cooldown",
    },
    {
      code: 6030,
      name: "MathOverflow",
      msg: "Arithmetic overflow",
    },
    {
      code: 6031,
      name: "NotImplemented",
      msg: "Not implemented yet",
    },
    {
      code: 6032,
      name: "DailyLossLimitExceeded",
      msg: "This swap's loss against the oracle would exceed the vault's daily loss limit",
    },
    {
      code: 6033,
      name: "PriceSkewTooLarge",
      msg: "The input and output price updates were published too far apart",
    },
  ],
  types: [
    {
      name: "AllowedMint",
      docs: ["A mint the vault may hold and swap, with the Pyth feed that prices it in USD."],
      type: {
        kind: "struct",
        fields: [
          {
            name: "mint",
            docs: ["Classic SPL Token mint (Token-2022 is rejected, design §6.8)."],
            type: "pubkey",
          },
          {
            name: "pyth_feed_id",
            docs: [
              "Pyth USD price feed ID for this mint, e.g. SOL/USD for wSOL. The swap reads the",
              "price only from an update for this feed, so the keeper cannot choose the price.",
            ],
            type: {
              array: ["u8", 32],
            },
          },
        ],
      },
    },
    {
      name: "ConfigUpdated",
      type: {
        kind: "struct",
        fields: [
          {
            name: "vault",
            type: "pubkey",
          },
          {
            name: "allowed_mints",
            type: {
              vec: {
                defined: {
                  name: "AllowedMint",
                },
              },
            },
          },
          {
            name: "max_slippage_bps",
            type: "u16",
          },
          {
            name: "max_oracle_staleness_secs",
            type: "u32",
          },
          {
            name: "strategy_hash",
            type: {
              array: ["u8", 32],
            },
          },
          {
            name: "max_daily_loss_usd",
            type: "u64",
          },
        ],
      },
    },
    {
      name: "Deposited",
      type: {
        kind: "struct",
        fields: [
          {
            name: "vault",
            type: "pubkey",
          },
          {
            name: "mint",
            type: "pubkey",
          },
          {
            name: "amount",
            type: "u64",
          },
          {
            name: "vault_balance",
            docs: ["Vault balance of `mint` after the deposit."],
            type: "u64",
          },
        ],
      },
    },
    {
      name: "InitializeVaultArgs",
      type: {
        kind: "struct",
        fields: [
          {
            name: "vault_id",
            type: "u64",
          },
          {
            name: "keeper",
            docs: ["`Pubkey::default()` for no keeper (swaps disabled until set_keeper)."],
            type: "pubkey",
          },
          {
            name: "allowed_mints",
            type: {
              vec: {
                defined: {
                  name: "AllowedMint",
                },
              },
            },
          },
          {
            name: "max_slippage_bps",
            type: "u16",
          },
          {
            name: "max_oracle_staleness_secs",
            type: "u32",
          },
          {
            name: "strategy_hash",
            type: {
              array: ["u8", 32],
            },
          },
          {
            name: "max_daily_loss_usd",
            docs: [
              "Most the vault may lose to swaps per 24 hours versus the oracle, in micro-USD.",
              "0 allows no loss at all (every swap must match or beat the oracle).",
            ],
            type: "u64",
          },
        ],
      },
    },
    {
      name: "KeeperChanged",
      type: {
        kind: "struct",
        fields: [
          {
            name: "vault",
            type: "pubkey",
          },
          {
            name: "old_keeper",
            type: "pubkey",
          },
          {
            name: "new_keeper",
            type: "pubkey",
          },
        ],
      },
    },
    {
      name: "PausedChanged",
      type: {
        kind: "struct",
        fields: [
          {
            name: "vault",
            type: "pubkey",
          },
          {
            name: "paused",
            type: "bool",
          },
        ],
      },
    },
    {
      name: "PriceFeedMessage",
      repr: {
        kind: "c",
      },
      type: {
        kind: "struct",
        fields: [
          {
            name: "feed_id",
            docs: [
              "`FeedId` but avoid the type alias because of compatibility issues with Anchor's `idl-build` feature.",
            ],
            type: {
              array: ["u8", 32],
            },
          },
          {
            name: "price",
            type: "i64",
          },
          {
            name: "conf",
            type: "u64",
          },
          {
            name: "exponent",
            type: "i32",
          },
          {
            name: "publish_time",
            docs: ["The timestamp of this price update in seconds"],
            type: "i64",
          },
          {
            name: "prev_publish_time",
            docs: [
              "The timestamp of the previous price update. This field is intended to allow users to",
              "identify the single unique price update for any moment in time:",
              "for any time t, the unique update is the one such that prev_publish_time < t <= publish_time.",
              "",
              "Note that there may not be such an update while we are migrating to the new message-sending logic,",
              "as some price updates on pythnet may not be sent to other chains (because the message-sending",
              "logic may not have triggered). We can solve this problem by making the message-sending mandatory",
              "(which we can do once publishers have migrated over).",
              "",
              "Additionally, this field may be equal to publish_time if the message is sent on a slot where",
              "where the aggregation was unsuccesful. This problem will go away once all publishers have",
              "migrated over to a recent version of pyth-agent.",
            ],
            type: "i64",
          },
          {
            name: "ema_price",
            type: "i64",
          },
          {
            name: "ema_conf",
            type: "u64",
          },
        ],
      },
    },
    {
      name: "PriceUpdateV2",
      docs: [
        "A price update account. This account is used by the Pyth Receiver program to store a verified price update from a Pyth price feed.",
        "It contains:",
        "- `write_authority`: The write authority for this account. This authority can close this account to reclaim rent or update the account to contain a different price update.",
        "- `verification_level`: The [`VerificationLevel`] of this price update. This represents how many Wormhole guardian signatures have been verified for this price update.",
        "- `price_message`: The actual price update.",
        "- `posted_slot`: The slot at which this price update was posted.",
      ],
      type: {
        kind: "struct",
        fields: [
          {
            name: "write_authority",
            type: "pubkey",
          },
          {
            name: "verification_level",
            type: {
              defined: {
                name: "VerificationLevel",
              },
            },
          },
          {
            name: "price_message",
            type: {
              defined: {
                name: "PriceFeedMessage",
              },
            },
          },
          {
            name: "posted_slot",
            type: "u64",
          },
        ],
      },
    },
    {
      name: "Swapped",
      docs: ["Everything needed to audit a swap against the oracle afterwards."],
      type: {
        kind: "struct",
        fields: [
          {
            name: "vault",
            type: "pubkey",
          },
          {
            name: "keeper",
            type: "pubkey",
          },
          {
            name: "input_mint",
            type: "pubkey",
          },
          {
            name: "output_mint",
            type: "pubkey",
          },
          {
            name: "spent",
            docs: ["Input actually spent (base units)."],
            type: "u64",
          },
          {
            name: "received",
            docs: ["Output actually received by the vault (base units)."],
            type: "u64",
          },
          {
            name: "oracle_out",
            docs: ["Output the oracle prices imply for `spent`, before slippage."],
            type: "u64",
          },
          {
            name: "min_out",
            docs: ["The minimum the swap had to meet."],
            type: "u64",
          },
          {
            name: "price_in",
            type: "i64",
          },
          {
            name: "price_in_expo",
            type: "i32",
          },
          {
            name: "price_out",
            type: "i64",
          },
          {
            name: "price_out_expo",
            type: "i32",
          },
          {
            name: "loss_usd",
            docs: [
              "This swap's shortfall versus the oracle, in micro-USD (0 if it met or beat it).",
            ],
            type: "u64",
          },
          {
            name: "loss_in_window_usd",
            docs: ["Losses in the current 24-hour window including this swap, in micro-USD."],
            type: "u64",
          },
        ],
      },
    },
    {
      name: "UpdateConfigArgs",
      docs: ["Fields left as `None` are unchanged."],
      type: {
        kind: "struct",
        fields: [
          {
            name: "allowed_mints",
            type: {
              option: {
                vec: {
                  defined: {
                    name: "AllowedMint",
                  },
                },
              },
            },
          },
          {
            name: "max_slippage_bps",
            type: {
              option: "u16",
            },
          },
          {
            name: "max_oracle_staleness_secs",
            type: {
              option: "u32",
            },
          },
          {
            name: "strategy_hash",
            type: {
              option: {
                array: ["u8", 32],
              },
            },
          },
          {
            name: "max_daily_loss_usd",
            docs: [
              "Micro-USD per 24 hours; takes effect immediately, losses already counted stay counted.",
            ],
            type: {
              option: "u64",
            },
          },
        ],
      },
    },
    {
      name: "Vault",
      docs: [
        'One owner\'s vault. PDA seeds: `["vault", owner, vault_id.to_le_bytes()]`.',
        "",
        "Tokens are held in the vault PDA's associated token accounts, one per mint. The owner",
        "deposits, withdraws and configures; the keeper may only swap between allowed mints.",
      ],
      type: {
        kind: "struct",
        fields: [
          {
            name: "owner",
            docs: ["Signs every instruction except `swap`. Immutable."],
            type: "pubkey",
          },
          {
            name: "vault_id",
            docs: ["Part of the PDA seeds, so one owner can have several vaults. Immutable."],
            type: "u64",
          },
          {
            name: "keeper",
            docs: ["The only key that may call `swap`. `Pubkey::default()` means no keeper."],
            type: "pubkey",
          },
          {
            name: "allowed_mints",
            docs: ["Mints the vault may receive by deposit or swap. No duplicates."],
            type: {
              vec: {
                defined: {
                  name: "AllowedMint",
                },
              },
            },
          },
          {
            name: "max_slippage_bps",
            docs: ["Largest shortfall a swap may have versus the oracle value, in bps."],
            type: "u16",
          },
          {
            name: "max_oracle_staleness_secs",
            docs: ["Oldest price a swap may use, in seconds."],
            type: "u32",
          },
          {
            name: "strategy_hash",
            docs: ["SHA-256 of the strategy JSON the owner approved. Informational, not enforced."],
            type: {
              array: ["u8", 32],
            },
          },
          {
            name: "paused",
            docs: ["When true, `swap` is blocked. Deposits and withdrawals still work."],
            type: "bool",
          },
          {
            name: "last_swap_ts",
            docs: ["Unix time of the last swap, for the swap cooldown."],
            type: "i64",
          },
          {
            name: "bump",
            docs: ["Canonical PDA bump."],
            type: "u8",
          },
          {
            name: "max_daily_loss_usd",
            docs: [
              "Most the vault may lose to swaps per 24 hours, versus the oracle, in micro-USD",
              "(USD × 10^6). Bounds what a compromised keeper can extract (security review H-1).",
            ],
            type: "u64",
          },
          {
            name: "loss_window_start",
            docs: ["Start (unix seconds) of the current 24-hour loss window."],
            type: "i64",
          },
          {
            name: "loss_in_window_usd",
            docs: ["Losses counted in the current window, in micro-USD."],
            type: "u64",
          },
          {
            name: "_reserved",
            docs: ["Space for future fields without reallocating."],
            type: {
              array: ["u8", 40],
            },
          },
        ],
      },
    },
    {
      name: "VaultInitialized",
      type: {
        kind: "struct",
        fields: [
          {
            name: "vault",
            type: "pubkey",
          },
          {
            name: "owner",
            type: "pubkey",
          },
          {
            name: "vault_id",
            type: "u64",
          },
          {
            name: "keeper",
            type: "pubkey",
          },
          {
            name: "allowed_mints",
            type: {
              vec: {
                defined: {
                  name: "AllowedMint",
                },
              },
            },
          },
          {
            name: "max_slippage_bps",
            type: "u16",
          },
          {
            name: "max_oracle_staleness_secs",
            type: "u32",
          },
          {
            name: "strategy_hash",
            type: {
              array: ["u8", 32],
            },
          },
          {
            name: "max_daily_loss_usd",
            type: "u64",
          },
        ],
      },
    },
    {
      name: "VerificationLevel",
      docs: [
        "Pyth price updates are bridged to all blockchains via Wormhole.",
        "Using the price updates on another chain requires verifying the signatures of the Wormhole guardians.",
        "The usual process is to check the signatures for two thirds of the total number of guardians, but this can be cumbersome on Solana because of the transaction size limits,",
        "so we also allow for partial verification.",
        "",
        "This enum represents how much a price update has been verified:",
        "- If `Full`, we have verified the signatures for two thirds of the current guardians.",
        "- If `Partial`, only `num_signatures` guardian signatures have been checked.",
        "",
        "# Warning",
        "Using partially verified price updates is dangerous, as it lowers the threshold of guardians that need to collude to produce a malicious price update.",
      ],
      type: {
        kind: "enum",
        variants: [
          {
            name: "Partial",
            fields: [
              {
                name: "num_signatures",
                type: "u8",
              },
            ],
          },
          {
            name: "Full",
          },
        ],
      },
    },
    {
      name: "Withdrawn",
      type: {
        kind: "struct",
        fields: [
          {
            name: "vault",
            type: "pubkey",
          },
          {
            name: "mint",
            type: "pubkey",
          },
          {
            name: "amount",
            type: "u64",
          },
          {
            name: "destination",
            type: "pubkey",
          },
          {
            name: "vault_balance",
            docs: ["Vault balance of `mint` after the withdrawal."],
            type: "u64",
          },
        ],
      },
    },
  ],
  constants: [
    {
      name: "LOSS_WINDOW_SECS",
      docs: ["Length of the window `max_daily_loss_usd` applies to (security review H-1)."],
      type: "i64",
      value: "86400",
    },
    {
      name: "MAX_CONFIDENCE_BPS",
      docs: [
        "Reject a price whose confidence interval is wider than 2% of the price (design §3, Q3).",
      ],
      type: "u64",
      value: "200",
    },
    {
      name: "MAX_PRICE_SKEW_SECS",
      docs: [
        "The input and output price updates of one swap must be published at most this far apart,",
        "so the keeper cannot pair prices from different moments (security review M-1).",
      ],
      type: "i64",
      value: "30",
    },
    {
      name: "MAX_SLIPPAGE_CAP_BPS",
      docs: ["Hard ceiling on `max_slippage_bps` an owner can set: 5% (design §3, Q2)."],
      type: "u16",
      value: "500",
    },
    {
      name: "MAX_STALENESS_CAP_SECS",
      docs: ["Hard ceiling on `max_oracle_staleness_secs` an owner can set (design §3, Q2)."],
      type: "u32",
      value: "120",
    },
    {
      name: "MIN_SWAP_INTERVAL_SECS",
      docs: ["Minimum time between swaps on one vault, limiting fee bleed (design §6.15, Q5)."],
      type: "i64",
      value: "60",
    },
    {
      name: "VAULT_SEED",
      docs: ['PDA seed prefix: `["vault", owner, vault_id.to_le_bytes()]`.'],
      type: "bytes",
      value: "[118, 97, 117, 108, 116]",
    },
  ],
} as unknown as Vault;
